template:
  path: fargate.yaml.j2
  type: file
parameters:
  SourceVersion: main
  EcrRepo: nuxeo/nuxeo_merritt
  ApplicationS3Bucket: pad-nuxeo
  DagsS3Bucket: pad-airflow

sceptre_user_data:
  ContainerEnvironment:
    - NUXEO_MERRITT_METADATA: {{ var.NUXEO_MERRITT_METADATA }}
    - NUXEO_MERRITT_MEDIA_JSON: {{ var.NUXEO_MERRITT_MEDIA_JSON }}
    - NUXEO_MERRITT_FEEDS: {{ var.NUXEO_MERRITT_FEEDS }}
    - NUXEO_MERRITT_NUXEO_TOKEN: {{ var.NUXEO_MERRITT_NUXEO_TOKEN }}
    - NUXEO_MERRITT_NUXEO_API: {{ var.NUXEO_MERRITT_NUXEO_API }}
    - NUXEO_MERRITT_REGISTRY_USER: {{ var.NUXEO_MERRITT_REGISTRY_USER }}
    - NUXEO_MERRITT_REGISTRY_API_KEY: {{ var.NUXEO_MERRITT_REGISTRY_API_KEY }}
